### ISSUE TITLE
Install Using Composer

### ISSUE THREAD

**Issue by VyasDhruv** [shoppingflux/module-magento2#4]
Is there any way to install this module using composer? If so then please provide the instructions for the same.

**Comment by benoit-apk** [comment]
Not currently, because the module is still in an early beta version, at least unless you explicitly specify the repository in your `composer.json` (see the [composer documentation](https://getcomposer.org/doc/05-repositories.md) about this feature).

In any case, we plan on releasing it on both packagist and the Magento marketplace once it will be stable enough, which should be imminent!
